// Generated by Skyramp v1.3.23 on 2026-05-12 00:56:08.237803819 +0000 UTC m=+341.614601215
// Command: skyramp generate contract rest http://localhost:5678/rest/scenario/executions/{id} \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_scenario_execution_by_id.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

// contract test for /rest/scenario/executions/{id} GET
test('testExecutionsIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const id = "99999";

    // Execute Request
    const executionsIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/rest/scenario/executions/{id}",
        method: "GET",
        headers: headers,
        pathParams: {"id": id}
    });

    // Generated Assertions
    expect(executionsIdGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(executionsIdGetResponse, 'id'), 'id').toBeGreaterThan(0);
    expect(getValue(executionsIdGetResponse, 'workflowId'), 'workflowId').not.toBeNull();
    expect(getValue(executionsIdGetResponse, 'mode'), 'mode').toMatch(/^(manual|trigger|webhook)$/);
    expect(getValue(executionsIdGetResponse, 'status'), 'status').toMatch(/^(running|success|error)$/);
    expect(getValue(executionsIdGetResponse, 'startedAt'), 'startedAt').toMatch(/^\d{4}-\d{2}-\d{2}T/);
});
