// Generated by Skyramp v1.3.23 on 2026-05-12 01:20:53.949375549 +0000 UTC m=+193.044357366
// Command: skyramp generate contract rest http://localhost:5678/rest/scenario/data-flow/simulate \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_scenario_data_flow_simulate_422.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"connections":{}} \
// 		--response-status-code 422 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

// contract test for /rest/scenario/data-flow/simulate POST
test('testSimulatePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const simulatePostRequestBody: string = `{
        "connections": {}
    }`;

    // Execute Request
    const simulatePostResponse = await client.sendRequest({
        url: URL,
        path: "/rest/scenario/data-flow/simulate",
        method: "POST",
        body: simulatePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(simulatePostResponse.statusCode, 'status code').toBe(422);
    expect(getValue(simulatePostResponse, 'message'), 'error message').not.toBeNull();
});
