// Generated by Skyramp v1.3.23 on 2026-05-12 00:56:10.606357877 +0000 UTC m=+343.983155285
// Command: skyramp generate contract rest http://localhost:5678/rest/scenario/executions/workflows/{workflowId} \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_scenario_executions_by_workflow.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--path-params workflowId=test-workflow-no-executions \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

// contract test for /rest/scenario/executions/workflows/{workflowId} GET
test('testWorkflowsWorkflowIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const workflowId = "test-workflow-no-executions";

    // Execute Request
    const workflowsWorkflowIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/rest/scenario/executions/workflows/{workflowId}",
        method: "GET",
        headers: headers,
        pathParams: {"workflowId": workflowId}
    });

    // Generated Assertions
    expect(workflowsWorkflowIdGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(workflowsWorkflowIdGetResponse, '0'), 'first item').toBeUndefined();
});
