// Generated by Skyramp v1.3.23 on 2026-05-12 00:56:05.850652195 +0000 UTC m=+339.227449592
// Command: skyramp generate contract rest http://localhost:5678/rest/scenario/executions/workflows/{workflowId}/execute \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_post_scenario_execute_422.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--path-params workflowId=test-workflow-123 \
// 		--provider \
// 		--request-data {"mode":"invalid-mode"} \
// 		--response-status-code 422 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

// contract test for /rest/scenario/executions/workflows/{workflowId}/execute POST
test('testExecutePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const workflowId = "test-workflow-123";

    // Request Body
    const executePostRequestBody: string = `{
        "mode": "invalid-mode"
    }`;

    // Execute Request
    const executePostResponse = await client.sendRequest({
        url: URL,
        path: "/rest/scenario/executions/workflows/{workflowId}/execute",
        method: "POST",
        body: executePostRequestBody,
        headers: headers,
        pathParams: {"workflowId": workflowId}
    });

    // Generated Assertions
    expect(executePostResponse.statusCode, 'status code').toBe(422);
});
