// Generated by Skyramp v1.3.23 on 2026-05-12 01:20:56.136971143 +0000 UTC m=+195.231952970
// Command: skyramp generate contract rest http://localhost:5678/rest/scenario/data-flow/validate/3 \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_scenario_data_flow_validate_200.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

// contract test for /rest/scenario/data-flow/validate/3 GET
test('testEndpoint3Get', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const endpoint3GetResponse = await client.sendRequest({
        url: URL,
        path: "/rest/scenario/data-flow/validate/3",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(endpoint3GetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(endpoint3GetResponse, 'data.success'), 'success').toBe(true);
    expect(getValue(endpoint3GetResponse, 'data.executionOrder').length, 'executionOrder length').toBe(3);
    expect(getValue(endpoint3GetResponse, 'data.executionOrder.0'), 'executionOrder[0]').toBe('Node_0');
    expect(getValue(endpoint3GetResponse, 'data.executionOrder.1'), 'executionOrder[1]').toBe('Node_1');
    expect(getValue(endpoint3GetResponse, 'data.executionOrder.2'), 'executionOrder[2]').toBe('Node_2');
    expect(getValue(endpoint3GetResponse, 'data.executionOrder.3'), 'executionOrder[3]').toBeUndefined();
    expect(getValue(endpoint3GetResponse, 'data.nodeOutputs.Node_2'), 'Node_2 output').not.toBeNull();
});
