// Generated by Skyramp v1.3.23 on 2026-05-12 01:21:16.084099802 +0000 UTC m=+215.179081639
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output simulate_post_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/n8n-testb/n8n-testb/packages/testing/playwright/tests/scenario_simulate-post-lifecycle.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5678");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const simulatePostRequestBody = `{
            "connections": {
                "Source": {
                    "main": [
                        [
                            {
                                "index": 0,
                                "node": "Transform",
                                "type": "main"
                            }
                        ]
                    ]
                }
            },
            "nodes": [
                {
                    "data": [
                        {
                            "json": {
                                "id": 42,
                                "value": "test-payload"
                            }
                        }
                    ],
                    "name": "Source",
                    "type": "trigger"
                },
                {
                    "name": "Transform",
                    "type": "set"
                }
            ]
        }`
    
    // Execute Request
    let simulatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/rest/scenario/data-flow/simulate",
        method:"POST",
        body:simulatePostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(simulatePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(simulatePostResponse, 'data.success'), 'success').toBe(true);
    expect(getValue(simulatePostResponse, 'data.executionOrder').length, 'executionOrder length').toBe(2);
    expect(getValue(simulatePostResponse, 'data.executionOrder.0'), 'executionOrder[0]').toBe('Source');
    expect(getValue(simulatePostResponse, 'data.executionOrder.1'), 'executionOrder[1]').toBe('Transform');
    expect(getValue(simulatePostResponse, 'data.executionOrder.2'), 'executionOrder[2]').toBeUndefined();
    expect(getValue(simulatePostResponse, 'data.nodeOutputs.Source.0.0.json.id'), 'Source output id').toBe(42);
    expect(getValue(simulatePostResponse, 'data.nodeOutputs.Source.0.0.json.value'), 'Source output value').toBe('test-payload');
    expect(getValue(simulatePostResponse, 'data.nodeOutputs.Transform.0.0.json.id'), 'Transform data flow id').toBe(42);
    expect(getValue(simulatePostResponse, 'data.nodeOutputs.Transform.0.0.json.value'), 'Transform data flow value').toBe('test-payload');
});

